org.gradle.jvmargs=-Xmx3g
android.useAndroidX=false
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
systemProp.http.proxyHost=hatch-egress-proxy
systemProp.http.proxyPort=3128
systemProp.http.proxyUser=hatch-runtime
systemProp.http.proxyPassword=ca10245db4064da0aa84097b0f5aae09
systemProp.https.proxyHost=hatch-egress-proxy
systemProp.https.proxyPort=3128
systemProp.https.proxyUser=hatch-runtime
systemProp.https.proxyPassword=ca10245db4064da0aa84097b0f5aae09
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1
